- group:    Enums & traits
  start:    06-10-2022 19:30
  deadline: 20-10-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: polka
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/polka
    - task: trust
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/trust

- group:    Borrowing & slices
  start:    29-09-2022 19:30
  deadline: 20-10-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: ini
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/ini
    - task: tar
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/tar

- group:    Starters
  start:    15-09-2022 19:30
  deadline: 29-09-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: comm
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/comm
    - task: perc
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/perc

- group:    Test
  start:    01-08-2022 18:00
  deadline: 22-09-2022 18:00
  enabled: true
  tasks:
    - task: add
      score: 0
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/add
