- group:    Threads & network
  start:    17-11-2022 19:30
  deadline: 01-12-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: threadpool
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/threadpool
    - task: tcp_proxy
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/tcp_proxy

- group:    Project 2
  start:    10-11-2022 19:30
  deadline: 01-12-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: orm
      score: 1
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/orm

- group:    Macros
  start:    03-11-2022 19:30
  deadline: 17-11-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: stdmacro
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/stdmacro
    - task: gc
      score: 300
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/gc

- group:    Functional
  start:    27-10-2022 19:30
  deadline: 10-11-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: itertools
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/itertools
    - task: fswalk
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/fswalk

- group:    Smart pointers
  start:    20-10-2022 19:30
  deadline: 03-11-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: mpsc
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/mpsc

- group:    Project 1
  start:    16-10-2022 12:00
  deadline: 06-11-2022 23:59
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: jsondb
      score: 1
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/jsondb

- group:    Generics
  start:    13-10-2022 19:30
  deadline: 27-10-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: flatmap
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/flatmap

- group:    Enums & traits
  start:    06-10-2022 19:30
  deadline: 20-10-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: polka
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/polka
    - task: trust
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/trust

- group:    Borrowing & slices
  start:    29-09-2022 19:30
  deadline: 20-10-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: ini
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/ini
    - task: tar
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/tar

- group:    Starters
  start:    15-09-2022 19:30
  deadline: 29-09-2022 19:30
  second_deadline: 31-01-2023 23:59
  enabled: true
  tasks:
    - task: comm
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/comm
    - task: perc
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/perc

- group:    Test
  start:    01-08-2022 18:00
  deadline: 22-09-2022 18:00
  enabled: true
  tasks:
    - task: add
      score: 0
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/add
