- group:    Borrowing & slices
  start:    29-09-2022 19:30
  deadline: 13-10-2022 19:30
  enabled: true
  tasks:
    - task: ini
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/ini
    - task: tar
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/tar

- group:    Starters
  start:    15-09-2022 19:30
  deadline: 29-09-2022 19:30
  enabled: true
  tasks:
    - task: comm
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/comm
    - task: perc
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/perc

- group:    Test
  start:    01-08-2022 18:00
  deadline: 22-09-2022 18:00
  enabled: true
  tasks:
    - task: add
      score: 0
      url: https://gitlab.manytask.org/rust-ysda/public-2022-fall/-/tree/master/add
