[workspace]
members = [
    # Tasks
    "add",
    "comm",
    "perc",
    "ini",
    "tar",
    "polka",
    "trust",
    "flatmap",
    "jsondb",
    "mpsc",
    "itertools",
    "fswalk",
    "stdmacro",
    "gc",

    # Tools
    "tools/submit",
]
